version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  crop-ai-service:
    image: garryrk/crop-ai-service:latest
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
